openapi: 3.0.3
info:
  title: Default Domain v2
  version: "5.0.0"
paths:
  /api/v1/lowerplural:
    get:
      tags:
        - UpperCamelSingular
      summary: List all the UpperCamelPlural
      operationId: v2.listUpperCamelPlural
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/sortBy'
        - $ref: '#/components/parameters/sortOrder'
        - $ref: '#/components/parameters/parentUpperCamelSingularId'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpperCamelSingularResponse.List.Envelope'
              example:
                command: listUpperCamelPlural
                httpStatus: OK
                message: Successfully executed listUpperCamelPlural
                params: {}
                responseObject: []
                success: true
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
              example:
                command: listUpperCamelPlural
                errors:
                  - Service returned Bad Request
                httpStatus: BAD_REQUEST
                message: Failed to execute listUpperCamelPlural
                params: {}
                responseObject: null
                success: false
                throwable:
                  message: Service returned Bad Request
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
              example:
                command: listUpperCamelPlural
                errors:
                  - Service returned Unauthorized
                httpStatus: UNAUTHORIZED
                message: Failed to execute listUpperCamelPlural
                params: {}
                responseObject: null
                success: false
                throwable:
                  message: Service returned Unauthorized
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
              example:
                command: listUpperCamelPlural
                errors:
                  - Service returned Forbidden
                httpStatus: FORBIDDEN
                message: Failed to execute listUpperCamelPlural
                params: {}
                responseObject: null
                success: false
                throwable:
                  message: Service returned Forbidden
      x-msx-permissions:
        - VIEW_SCREAMING_SNAKE_PLURAL
      x-msx-action: list
    post:
      tags:
        - UpperCamelSingular
      summary: Create a new UpperCamelSingular
      operationId: v2.createUpperCamelSingular
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpperCamelSingularCreateRequest'
            example:
              data: ""
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpperCamelSingularResponse.Envelope'
              example:
                command: createUpperCamelPlural
                httpStatus: OK
                message: Successfully executed createUpperCamelPlural
                params: {}
                responseObject: []
                success: true
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpperCamelSingularResponse.Envelope'
              example:
                command: createUpperCamelPlural
                httpStatus: CREATED
                message: Successfully executed createUpperCamelPlural
                params: {}
                responseObject: []
                success: true
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
              example:
                command: createUpperCamelPlural
                httpStatus: BAD_REQUEST
                message: Failed to execute createUpperCamelPlural
                params: { }
                responseObject: null
                success: false
                throwable:
                  message: Service returned Bad Request
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
              example:
                command: createUpperCamelPlural
                httpStatus: UNAUTHORIZED
                message: Failed to execute createUpperCamelPlural
                params: { }
                responseObject: null
                success: false
                throwable:
                  message: Service returned Unauthorized
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
              example:
                command: createUpperCamelPlural
                httpStatus: FORBIDDEN
                message: Failed to execute createUpperCamelPlural
                params: { }
                responseObject: null
                success: false
                throwable:
                  message: Service returned Forbidden
      x-msx-permissions:
        - MANAGE_SCREAMING_SNAKE_PLURAL
      x-msx-action: create
  /api/v1/lowerplural/{lowerCamelSingularId}:
    delete:
      tags:
        - UpperCamelSingular
      summary: Delete the specified UpperCamelSingular
      operationId: v2.deleteUpperCamelSingular
      parameters:
        - $ref: '#/components/parameters/lowerCamelSingularId'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
      x-msx-permissions:
        - MANAGE_SCREAMING_SNAKE_PLURAL
      x-msx-action: delete
    get:
      tags:
        - UpperCamelSingular
      summary: Retrieve the specified UpperCamelSingular
      operationId: v2.getUpperCamelSingular
      parameters:
        - $ref: '#/components/parameters/lowerCamelSingularId'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpperCamelSingularResponse.Envelope'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
      x-msx-permissions:
        - VIEW_SCREAMING_SNAKE_PLURAL
      x-msx-action: retrieve
    put:
      tags:
        - UpperCamelSingular
      summary: Update the specified UpperCamelSingular
      operationId: v2.updateUpperCamelSingular
      parameters:
        - $ref: '#/components/parameters/lowerCamelSingularId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpperCamelSingularUpdateRequest'
            example:
              data: ""
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpperCamelSingularResponse.Envelope'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/types.Void.Envelope'
      x-msx-permissions:
        - MANAGE_SCREAMING_SNAKE_PLURAL
      x-msx-action: update
components:
  schemas:
    Binary:
      title: Binary
      type: string
      format: binary
    UUID:
      title: UUID
      pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
      type: string
      format: uuid
      example: 123e4567-e89b-12d3-a456-426614174000
    integration.MsxEnvelope:
      required:
        - command
        - httpStatus
        - message
        - responseObject
        - success
      type: object
      properties:
        command:
          type: string
        debug:
          type: object
          additionalProperties: {}
        errors:
          type: array
          items:
            type: string
        httpStatus:
          type: string
        message:
          type: string
        params:
          type: object
          additionalProperties: {}
          nullable: true
        responseObject: {}
        success:
          type: boolean
        throwable:
          $ref: '#/components/schemas/integration.Throwable'
    integration.Throwable:
      required:
        - message
      type: object
      properties:
        cause:
          $ref: '#/components/schemas/integration.Throwable'
        message:
          type: string
        stackTrace:
          type: array
          items:
            $ref: '#/components/schemas/types.BackTraceFrame'
    types.BackTraceFrame:
      title: BackTraceFrame
      required:
        - methodName
        - fullMethodName
        - fullFileName
        - fileName
        - lineNumber
      type: object
      properties:
        fileName:
          type: string
        fullFileName:
          type: string
        fullMethodName:
          type: string
        lineNumber:
          type: integer
        methodName:
          type: string
    types.Empty:
      title: Empty
      type: object
    types.Void.Envelope:
      title: types.Void.Envelope
      allOf:
        - $ref: '#/components/schemas/integration.MsxEnvelope'
    UpperCamelSingularCreateRequest:
      title: UpperCamelSingularCreateRequest
      required:
        - data
      type: object
      properties:
        data:
          type: string
    UpperCamelSingularResponse:
      title: UpperCamelSingularResponse
      required:
        - lowerCamelSingularId
        - data
      type: object
      properties:
        data:
          type: string
        lowerCamelSingularId:
          $ref: '#/components/schemas/UUID'
      x-msx-actions:
        - create
        - update
        - list
        - retrieve
    UpperCamelSingularResponse.List:
      title: UpperCamelSingularResponse.List
      type: array
      items:
        $ref: '#/components/schemas/UpperCamelSingularResponse'
    UpperCamelSingularResponse.List.Envelope:
      title: UpperCamelSingularResponse.List.Envelope
      allOf:
        - $ref: '#/components/schemas/integration.MsxEnvelope'
        - type: object
          properties:
            responseObject:
              $ref: '#/components/schemas/UpperCamelSingularResponse.List'
    UpperCamelSingularResponse.Envelope:
      title: UpperCamelSingularResponse.Envelope
      allOf:
        - $ref: '#/components/schemas/integration.MsxEnvelope'
        - type: object
          x-msx-injected-property: responseObject
          properties:
            responseObject:
              $ref: '#/components/schemas/UpperCamelSingularResponse'
    UpperCamelSingularUpdateRequest:
      title: UpperCamelSingularUpdateRequest
      required:
        - data
      type: object
      properties:
        data:
          type: string
  parameters:
    lowerCamelSingularId:
      name: lowerCamelSingularId
      in: path
      description: Retrieve the lowerCamelSingular with the specified id
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/UUID'
    page:
      name: page
      in: query
      required: true
      style: form
      explode: false
      schema:
        minimum: 0
        type: integer
        format: int32
        default: 0
      example: "0"
    pageSize:
      name: pageSize
      in: query
      required: true
      style: form
      explode: false
      schema:
        minimum: 1
        type: integer
        format: int32
        default: 100
      example: "100"
    parentUpperCamelSingularId:
      name: parentId
      in: query
      description: Filter by children of specified parent
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/UUID'
    sortBy:
      name: sortBy
      in: query
      style: form
      explode: false
      schema:
        type: string
        default: ""
    sortOrder:
      name: sortOrder
      in: query
      style: form
      explode: false
      schema:
        enum:
          - asc
          - desc
        type: string
        default: asc
